// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKSzUZxxvVbO1afHStUHickCdkdLfntLM',
    appId: '1:944241438394:web:8e2bfb32f8dd824af3dc83',
    messagingSenderId: '944241438394',
    projectId: 'authproject-cc9c4',
    authDomain: 'authproject-cc9c4.firebaseapp.com',
    storageBucket: 'authproject-cc9c4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGuFPnOKNSyozU44WILhSNxu0M_kyFV08',
    appId: '1:944241438394:android:55ccb5d3bfe6a86bf3dc83',
    messagingSenderId: '944241438394',
    projectId: 'authproject-cc9c4',
    storageBucket: 'authproject-cc9c4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxFtWQLwDsJyXIW9Jkh05rf5HSFa2M1c4',
    appId: '1:944241438394:ios:22b3dc015c66264df3dc83',
    messagingSenderId: '944241438394',
    projectId: 'authproject-cc9c4',
    storageBucket: 'authproject-cc9c4.firebasestorage.app',
    iosBundleId: 'com.example.authProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxFtWQLwDsJyXIW9Jkh05rf5HSFa2M1c4',
    appId: '1:944241438394:ios:22b3dc015c66264df3dc83',
    messagingSenderId: '944241438394',
    projectId: 'authproject-cc9c4',
    storageBucket: 'authproject-cc9c4.firebasestorage.app',
    iosBundleId: 'com.example.authProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKSzUZxxvVbO1afHStUHickCdkdLfntLM',
    appId: '1:944241438394:web:286e112f5f57f06ff3dc83',
    messagingSenderId: '944241438394',
    projectId: 'authproject-cc9c4',
    authDomain: 'authproject-cc9c4.firebaseapp.com',
    storageBucket: 'authproject-cc9c4.firebasestorage.app',
  );
}
